#!/usr/bin/env bash
#INSTALL_PATH="$(realpath $0 | grep .*docker-swarm -o)"
INSTALL_PATH="/opt/docker-swarm"
source ${INSTALL_PATH}/scripts/general_functions.sh

case $1 in
  start)
		COMMAND="/scripts/start.sh $(echo $@ | sed "s/$1//g")"
		;;
	stop)
		COMMAND="/scripts/stop.sh $(echo $@ | sed "s/$1//g")"
		;;
	backup)
        PARAMETERS=$@
        EXPRESSION_BKP="$(echo "$@" | grep -o -P '(?<=--expression ).*' | sed 's/--.*//g')"

        if [ "${EXPRESSION_BKP}" ];then
            PARAMETERS="$(echo -e "$@" \
                | sed 's/\-\-/\n\-\-/g' \
                | sed '/expression/d' \
                | sed -z 's/\n//g') --expression \"${EXPRESSION_BKP}\""
        fi

		COMMAND="/scripts/volumes.sh ${PARAMETERS}"
		;;
	restore)
		COMMAND="/scripts/volumes.sh $@"
		;;
  update-images)
		COMMAND="/scripts/update.sh $(echo $@ | sed "s/$1//g")"
		;;
  monitor)
		COMMAND="/scripts/monitor.sh $(echo $@ | sed "s/$1//g")"
		;;
  uninstall)
		COMMAND="/scripts/uninstall.sh $(echo $@ | sed "s/$1//g")"
		;;
	edit-config)
	  vi ${INSTALL_PATH}/.env
		set_variables_environment
		exit
		;;
  update-project)
    if [ "$EUID" -ne 0 ]; then
      echo "Please run as root"
      exit
    fi

    sudo git -C ${INSTALL_PATH} reset --hard HEAD > /dev/null
    sudo git -C ${INSTALL_PATH} pull -f > /dev/null

    if [ $? = 0 ];then
      echo "Project updated successfully!"
    fi
		exit
		;;
	*)
		echo "Sorry, I don't understand"
		exit
		;;
esac

bash -c "${INSTALL_PATH}${COMMAND}"
