#!/usr/bin/env bash

INSTALL_PATH="/opt/ocariot-swarm"
source ${INSTALL_PATH}/scripts/general_functions.sh

edit_config()
{
  # Verifying the existence of .env|.env.example file
  if [ ! $(find ${INSTALL_PATH} -name $1) ]
  then
    cp ${INSTALL_PATH}/$1.example ${INSTALL_PATH}/$1
  fi

  editor ${INSTALL_PATH}/$1
  set -a && . ${INSTALL_PATH}/.$1 && set +a
}

get_last_tag()
{
   JSON=$(curl -s https://api.github.com/repos/ocariot/docker-swarm/releases/latest)
   echo ${JSON} | grep -oP '(?<="tag_name": ")[^"]*'
}

stack_options()
{
  case $1 in
      start)
        COMMAND="/scripts/stack/start.sh $(echo $@ | sed "s/$1//g")"
        ;;
      stop)
        COMMAND="/scripts/stack/stop.sh $(echo $@ | sed "s/$1//g")"
        ;;
      backup)
        PARAMETERS=$@

        if [ "${EXPRESSION_BKP}" ];then
          PARAMETERS="$(echo -e "$@" \
            | sed 's/\-\-/\n\-\-/g' \
            | sed '/expression/d' \
            | sed -z 's/\n//g') --expression \"${EXPRESSION_BKP}\""
        fi

        COMMAND="/scripts/stack/volumes.sh ${PARAMETERS}"
        ;;
      restore)
        COMMAND="/scripts/stack/volumes.sh $@"
        ;;
      update-images)
        COMMAND="/scripts/stack/update-images.sh $(echo $@ | sed "s/$1//g")"
        ;;
      edit-config)
        edit_config ${ENV_OCARIOT}
        exit
        ;;
			*)
        stack_help
        ;;
    esac
}

monitor_options()
{
  case $1 in
      start)
        COMMAND="/scripts/monitor/start.sh $(echo $@ | sed "s/$1//g")"
        ;;
      stop)
        COMMAND="/scripts/monitor/stop.sh $(echo $@ | sed "s/$1//g")"
        ;;
      backup)
        PARAMETERS=$@

        if [ "${EXPRESSION_BKP}" ];then
          PARAMETERS="$(echo -e "$@" \
            | sed 's/\-\-/\n\-\-/g' \
            | sed '/expression/d' \
            | sed -z 's/\n//g') --expression \"${EXPRESSION_BKP}\""
        fi

        COMMAND="/scripts/monitor/volumes.sh ${PARAMETERS}"
        ;;
      restore)
        COMMAND="/scripts/monitor/volumes.sh $@"
        ;;
      edit-config)
        edit_config ${ENV_MONITOR}
        exit
        ;;
      *)
        monitor_help
        ;;
  esac
}

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

case $1 in
  uninstall)
		COMMAND="/scripts/uninstall.sh $(echo $@ | sed "s/$1//g")"
		;;
  update)
    LAST_TAG=$(get_last_tag)
    sudo git -C ${INSTALL_PATH} reset --hard HEAD &> /dev/null
    sudo git -C ${INSTALL_PATH} fetch &> /dev/null
    sudo git -C ${INSTALL_PATH} checkout "tags/${LAST_TAG}" &> /dev/null

    if [ ${LAST_TAG} = $(git -C ${INSTALL_PATH} describe --tags --abbrev=0) ];then
      echo "OCARIoT Project updated successfully!"
    else
      echo "OCARIoT Project wasn't updated with success!"
    fi
		exit
		;;
  stack)
    EXPRESSION_BKP="$(echo "$@" | grep -o -P '(?<=--expression ).*' | sed 's/--.*//g')"
		stack_options $(echo $@ | sed "s/$1 //g")
		;;
  monitor)
    monitor_options $(echo $@ | sed "s/$1 //g")
		;;
  version)
    echo "Version: $(git -C ${INSTALL_PATH} describe --tags --abbrev=0)"
    exit
    ;;
  *)
		ocariot_help
		;;
esac

bash -c "${INSTALL_PATH}${COMMAND}"
